version: "3.9"
services:
  lighttpd-webdav:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./example/webroot:/mnt
      - ./example/lighttpd.auth:/etc/lighttpd.auth:ro
