name: Create and publish a Docker image

on:
  push:
  schedule:
    - cron: "17 17 * * *" # Run at 17:17 every day

env:
  REGISTRY: ghcr.io
  DOCKERFILE: Dockerfile
  IMAGE_TAG: kizzycode/webdav-fileserver:latest

jobs:
  build-and-push-image:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Build and push docker
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            LIGHTTPD_CONFIG="./files/lighttpd.conf"
